### ISSUE TITLE
npm run test - Error: Exceeds block gas limit

### ISSUE THREAD

**Issue by marsrobertson** [aragon/aragon-court#35]
Added to scripts:

```
  "scripts": {
    "test": "TRUFFLE_TEST=true npm run ganache-cli:test",
    "analysis:tree": "TRUFFLE_TEST=true SUMTREE_GAS_ANALYSIS=true npm run ganache-cli:test",
    "ganache-cli:test": "./node_modules/@aragon/test-helpers/ganache-cli.sh",
    "version": "./node_modules/ganache-cli/cli.js --version"
  },
```

```
npm run version

> @aragon/court@1.0.0 version /Users/ms/Code/aragon-court
> ./node_modules/ganache-cli/cli.js --version

Ganache CLI v6.4.3 (ganache-core: 2.5.5)
```

### When trying to run tests getting:

```
Error: Exceeds block gas limit
    at Object.InvalidResponse (/Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/Users/ms/Code/aragon-court/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by bingen** [comment]
This may be related to this: https://github.com/aragon/aragon-court/issues/8#issuecomment-490975093

**Comment by sohkai** [comment]
@bingen I believe this has been fixed?

**Comment by bingen** [comment]
Maybe, assuming it was the same problem, but hasn't been merged yet.

**Comment by facuspagnuolo** [comment]
Closing, since it is already fixed. Thanks!
